name: 'dw1'
version: '1.0.0'
config-version: 2

profile:  'dw1'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  dw1:
    silver:
      +schema:  silver
      +materialized: incremental
    curated:
      +schema: curated
      +materialized: table