{{ config(materialized='table', schema='silver') }}

SELECT * FROM (VALUES
    ('SOFTWARE_ENGINEER'),
    ('BUSINESS_OWNER'),
    ('MEDICAL_PROFESSIONAL'),
    ('ACCOUNTANT'),
    ('RETIRED'),
    ('FINANCIAL_ANALYST'),
    ('MILITARY'),
    ('CONSULTANT'),
    ('LAWYER'),
    ('ENGINEER'),
    ('MARKETING'),
    ('GOVERNMENT'),
    ('EDUCATION'),
    ('SALES'),
    ('MANAGER'),
    ('EXECUTIVE'),
    ('ARCHITECT'),
    ('DESIGNER'),
    ('RESEARCHER'),
    ('ANALYST'),
    ('TRADER'),
    ('BROKER'),
    ('CONTRACTOR'),
    ('FREELANCER'),
    ('ARTIST'),
    ('WRITER'),
    ('UNEMPLOYED'),
    ('STUDENT'),
    ('HOMEMAKER'),
    ('OTHER')
) AS t(code)