{{ config(materialized='table', schema='silver') }}

SELECT * FROM (VALUES
    ('TECHNOLOGY'),
    ('FINANCE'),
    ('HEALTHCARE'),
    ('REAL_ESTATE'),
    ('MANUFACTURING'),
    ('RETAIL'),
    ('WHOLESALE'),
    ('CONSTRUCTION'),
    ('TRANSPORTATION'),
    ('HOSPITALITY'),
    ('EDUCATION'),
    ('GOVERNMENT'),
    ('LEGAL'),
    ('CONSULTING'),
    ('ADVERTISING'),
    ('MEDIA'),
    ('TELECOMMUNICATIONS'),
    ('ENERGY'),
    ('UTILITIES'),
    ('AGRICULTURE'),
    ('MINING'),
    ('AUTOMOTIVE'),
    ('AEROSPACE'),
    ('PHARMACEUTICAL'),
    ('BIOTECHNOLOGY'),
    ('ENTERTAINMENT'),
    ('FOOD_BEVERAGE'),
    ('TEXTILE'),
    ('CHEMICAL'),
    ('INSURANCE'),
    ('OTHER')
) AS t(code)