{{
    config(
        materialized='table',
        schema='gold',
        tags=['gold', 'dimension', 'scd2'],
        post_hook=[
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_version_num ON {{ this }} (customer_id, version_num)",
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_one_current_per_customer ON {{ this }} (customer_id) WHERE is_current = TRUE"
        ]
    )
}}

-- ====================================================================
-- Gold Layer:  SCD Type 2 Customer Profile Dimension
-- ====================================================================
-- Strategy: Full rebuild (simple and correct for initial implementation)
-- Source: silver.customer_profile_standardized
-- Change Detection: profile_hash comparison
-- ====================================================================

WITH silver_source AS (
    -- Get all records from Silver
    SELECT 
        customer_id,
        evidence_unique_key,
        firstname,
        lastname,
        firstname_local,
        lastname_local,
        person_title,
        person_title_other,
        marital_status,
        nationality,
        nationality_other,
        occupation,
        occupation_other,
        education_level,
        education_level_other,
        business_type,
        business_type_other,
        birthdate,
        total_asset,
        monthly_income,
        income_country,
        income_country_other,
        source_of_income_list,
        purpose_of_investment_list,
        profile_hash,
        source_of_income_set_hash,
        purpose_of_investment_set_hash,
        data_quality_score,
        _silver_dq_status,
        last_modified_ts,
        _bronze_batch_id
    FROM {{ ref('customer_profile_standardized') }}
),

-- Detect changes by comparing profile_hash
with_change_detection AS (
    SELECT 
        *,
        -- Detect if profile_hash changed from previous record
        LAG(profile_hash) OVER (
            PARTITION BY customer_id 
            ORDER BY last_modified_ts
        ) AS prev_profile_hash,
        
        -- Assign version number (restarts at 1 for each customer)
        ROW_NUMBER() OVER (
            PARTITION BY customer_id 
            ORDER BY last_modified_ts
        ) AS version_num
        
    FROM silver_source
),

-- Filter to only records where profile changed (or first record)
profile_versions AS (
    SELECT *
    FROM with_change_detection
    WHERE 
        -- First version for customer
        prev_profile_hash IS NULL
        -- OR profile changed
        OR profile_hash != prev_profile_hash
),

-- Compute SCD2 temporal columns
with_scd2_dates AS (
    SELECT 
        *,
        
        -- effective_start_ts = this version's source timestamp
        last_modified_ts AS effective_start_ts,
        
        -- effective_end_ts = next version's timestamp - 1 microsecond (NULL if current)
        LEAD(last_modified_ts) OVER (
            PARTITION BY customer_id 
            ORDER BY last_modified_ts
        ) - INTERVAL '1 microsecond' AS effective_end_ts,
        
        -- is_current = TRUE if this is the latest version
        CASE 
            WHEN LEAD(last_modified_ts) OVER (
                PARTITION BY customer_id 
                ORDER BY last_modified_ts
            ) IS NULL THEN TRUE
            ELSE FALSE
        END AS is_current
        
    FROM profile_versions
),

final AS (
    SELECT 
        -- Surrogate key (auto-generated by BIGSERIAL in DDL)
        ROW_NUMBER() OVER (ORDER BY customer_id, effective_start_ts) AS customer_profile_version_sk,
        
        -- Natural key
        customer_id,
        
        -- Profile attributes (Type 2 - versioned)
        evidence_unique_key,
        firstname,
        lastname,
        firstname_local,
        lastname_local,
        person_title,
        marital_status,
        nationality,
        occupation,
        education_level,
        business_type,
        birthdate,
        total_asset,
        monthly_income,
        income_country,
        
        -- Freetext fields (Type 1 - NOT versioned)
        person_title_other,
        nationality_other,
        occupation_other,
        education_level_other,
        business_type_other,
        income_country_other,
        
        -- Hashes
        profile_hash,
        source_of_income_set_hash,
        purpose_of_investment_set_hash,
        
        -- Data Quality Metrics (Type 1)
        data_quality_score,
        _silver_dq_status AS data_quality_status,
        
        -- Version management
        version_num,
        
        -- SCD2 temporal columns
        effective_start_ts,
        effective_end_ts,
        is_current,
        
        -- ETL metadata
        CURRENT_TIMESTAMP AS load_ts
        
    FROM with_scd2_dates
)

SELECT * FROM final