{{
    config(
        materialized='incremental',
        unique_key='audit_event_id',
        schema='gold',
        tags=['gold', 'fact', 'audit']
    )
}}

-- ====================================================================
-- Gold Layer:  Fact Customer Profile Audit
-- ====================================================================
-- Tracks profile change events (what changed, when, old vs new values)
-- Generated by comparing consecutive versions in dim_customer_profile
-- ====================================================================

WITH dim_all_versions AS (
    SELECT 
        customer_profile_version_sk,
        customer_id,
        version_num,
        
        -- Scalar attributes (for change detection)
        firstname,
        lastname,
        firstname_local,
        lastname_local,
        person_title,
        person_title_other,
        marital_status,
        nationality,
        nationality_other,
        occupation,
        occupation_other,
        education_level,
        education_level_other,
        business_type,
        business_type_other,
        birthdate,
        total_asset,
        monthly_income,
        income_country,
        income_country_other,
        
        -- Hashes (for change detection)
        profile_hash,
        source_of_income_set_hash,
        purpose_of_investment_set_hash,
        
        -- Data quality
        data_quality_score,
        data_quality_status,
        
        -- Temporal
        effective_start_ts,
        effective_end_ts,
        is_current
    FROM {{ ref('dim_customer_profile') }}
    
    {% if is_incremental() %}
    -- Only process new versions
    WHERE effective_start_ts > (SELECT COALESCE(MAX(effective_start_ts_new), '1900-01-01':: TIMESTAMP) FROM {{ this }})
    {% endif %}
),

-- ====================================================================
-- Self-join to compare consecutive versions
-- ====================================================================
version_pairs AS (
    SELECT 
        curr. customer_profile_version_sk AS customer_profile_version_sk_new,
        prev.customer_profile_version_sk AS customer_profile_version_sk_old,
        curr.customer_id,
        curr.version_num AS version_num_new,
        prev.version_num AS version_num_old,
        
        -- Old values (previous version)
        prev.firstname AS old_firstname,
        prev.lastname AS old_lastname,
        prev.firstname_local AS old_firstname_local,
        prev.lastname_local AS old_lastname_local,
        prev.person_title AS old_person_title,
        prev. person_title_other AS old_person_title_other,
        prev.marital_status AS old_marital_status,
        prev.nationality AS old_nationality,
        prev.nationality_other AS old_nationality_other,
        prev.occupation AS old_occupation,
        prev.occupation_other AS old_occupation_other,
        prev.education_level AS old_education_level,
        prev. education_level_other AS old_education_level_other,
        prev.business_type AS old_business_type,
        prev. business_type_other AS old_business_type_other,
        prev.birthdate AS old_birthdate,
        prev.total_asset AS old_total_asset,
        prev.monthly_income AS old_monthly_income,
        prev.income_country AS old_income_country,
        prev. income_country_other AS old_income_country_other,
        
        -- New values (current version)
        curr.firstname AS new_firstname,
        curr.lastname AS new_lastname,
        curr.firstname_local AS new_firstname_local,
        curr.lastname_local AS new_lastname_local,
        curr.person_title AS new_person_title,
        curr.person_title_other AS new_person_title_other,
        curr.marital_status AS new_marital_status,
        curr.nationality AS new_nationality,
        curr.nationality_other AS new_nationality_other,
        curr.occupation AS new_occupation,
        curr.occupation_other AS new_occupation_other,
        curr.education_level AS new_education_level,
        curr.education_level_other AS new_education_level_other,
        curr.business_type AS new_business_type,
        curr.business_type_other AS new_business_type_other,
        curr.birthdate AS new_birthdate,
        curr.total_asset AS new_total_asset,
        curr.monthly_income AS new_monthly_income,
        curr.income_country AS new_income_country,
        curr.income_country_other AS new_income_country_other,
        
        -- Hashes
        prev.profile_hash AS old_profile_hash,
        curr.profile_hash AS new_profile_hash,
        prev.source_of_income_set_hash AS old_source_of_income_set_hash,
        curr.source_of_income_set_hash AS new_source_of_income_set_hash,
        prev.purpose_of_investment_set_hash AS old_purpose_of_investment_set_hash,
        curr.purpose_of_investment_set_hash AS new_purpose_of_investment_set_hash,
        
        -- Data Quality
        prev.data_quality_score AS old_data_quality_score,
        curr.data_quality_score AS new_data_quality_score,
        prev. data_quality_status AS old_data_quality_status,
        curr.data_quality_status AS new_data_quality_status,
        
        -- Timestamps
        curr.effective_start_ts AS effective_start_ts_new,
        prev.effective_end_ts AS effective_end_ts_old,
        curr.effective_start_ts AS event_ts
        
    FROM dim_all_versions curr
    LEFT JOIN dim_all_versions prev
        ON curr.customer_id = prev.customer_id
        AND curr.version_num = prev.version_num + 1
),

-- ====================================================================
-- Detect which scalar fields changed
-- ====================================================================
with_change_detection AS (
    SELECT 
        *,
        
        -- Build array of changed field names
        ARRAY_REMOVE(ARRAY[
            CASE WHEN COALESCE(old_firstname, '') != COALESCE(new_firstname, '') THEN 'firstname' END,
            CASE WHEN COALESCE(old_lastname, '') != COALESCE(new_lastname, '') THEN 'lastname' END,
            CASE WHEN COALESCE(old_firstname_local, '') != COALESCE(new_firstname_local, '') THEN 'firstname_local' END,
            CASE WHEN COALESCE(old_lastname_local, '') != COALESCE(new_lastname_local, '') THEN 'lastname_local' END,
            CASE WHEN COALESCE(old_person_title, '') != COALESCE(new_person_title, '') THEN 'person_title' END,
            CASE WHEN COALESCE(old_person_title_other, '') != COALESCE(new_person_title_other, '') THEN 'person_title_other' END,
            CASE WHEN COALESCE(old_marital_status, '') != COALESCE(new_marital_status, '') THEN 'marital_status' END,
            CASE WHEN COALESCE(old_nationality, '') != COALESCE(new_nationality, '') THEN 'nationality' END,
            CASE WHEN COALESCE(old_nationality_other, '') != COALESCE(new_nationality_other, '') THEN 'nationality_other' END,
            CASE WHEN COALESCE(old_occupation, '') != COALESCE(new_occupation, '') THEN 'occupation' END,
            CASE WHEN COALESCE(old_occupation_other, '') != COALESCE(new_occupation_other, '') THEN 'occupation_other' END,
            CASE WHEN COALESCE(old_education_level, '') != COALESCE(new_education_level, '') THEN 'education_level' END,
            CASE WHEN COALESCE(old_education_level_other, '') != COALESCE(new_education_level_other, '') THEN 'education_level_other' END,
            CASE WHEN COALESCE(old_business_type, '') != COALESCE(new_business_type, '') THEN 'business_type' END,
            CASE WHEN COALESCE(old_business_type_other, '') != COALESCE(new_business_type_other, '') THEN 'business_type_other' END,
            CASE WHEN old_birthdate != new_birthdate THEN 'birthdate' END,
            CASE WHEN COALESCE(old_total_asset, '') != COALESCE(new_total_asset, '') THEN 'total_asset' END,
            CASE WHEN COALESCE(old_monthly_income, '') != COALESCE(new_monthly_income, '') THEN 'monthly_income' END,
            CASE WHEN COALESCE(old_income_country, '') != COALESCE(new_income_country, '') THEN 'income_country' END,
            CASE WHEN COALESCE(old_income_country_other, '') != COALESCE(new_income_country_other, '') THEN 'income_country_other' END
        ], NULL) AS changed_fields_array,
        
        -- Detect set changes
        ARRAY_REMOVE(ARRAY[
            CASE WHEN old_source_of_income_set_hash != new_source_of_income_set_hash THEN 'source_of_income' END,
            CASE WHEN old_purpose_of_investment_set_hash != new_purpose_of_investment_set_hash THEN 'purpose_of_investment' END
        ], NULL) AS changed_sets_array
        
    FROM version_pairs
),

-- ====================================================================
-- Build JSON representations of changes
-- ====================================================================
with_json_values AS (
    SELECT 
        *,
        
        -- Convert field array to JSON array string
        CASE 
            WHEN version_num_old IS NULL THEN '[]':: TEXT
            WHEN ARRAY_LENGTH(changed_fields_array, 1) IS NULL THEN '[]'::TEXT
            ELSE 
                '[' || ARRAY_TO_STRING(
                    ARRAY(
                        SELECT '"' || unnest || '"' 
                        FROM UNNEST(changed_fields_array)
                    ), 
                    ','
                ) || ']'
        END AS changed_scalar_attributes_json,
        
        -- Convert set array to JSON array string
        CASE 
            WHEN version_num_old IS NULL THEN '[]'::TEXT
            WHEN ARRAY_LENGTH(changed_sets_array, 1) IS NULL THEN '[]'::TEXT
            ELSE 
                '[' || ARRAY_TO_STRING(
                    ARRAY(
                        SELECT '"' || unnest || '"' 
                        FROM UNNEST(changed_sets_array)
                    ), 
                    ','
                ) || ']'
        END AS changed_set_names_json,
        
        -- Build JSON object of old values (only for changed fields)
        CASE 
            WHEN version_num_old IS NULL THEN NULL
            WHEN ARRAY_LENGTH(changed_fields_array, 1) IS NULL THEN '{}'::TEXT
            ELSE 
                '{' || ARRAY_TO_STRING(
                    ARRAY_REMOVE(ARRAY[
                        CASE WHEN 'firstname' = ANY(changed_fields_array) 
                            THEN '"firstname":"' || COALESCE(old_firstname, '') || '"' END,
                        CASE WHEN 'lastname' = ANY(changed_fields_array) 
                            THEN '"lastname":"' || COALESCE(old_lastname, '') || '"' END,
                        CASE WHEN 'marital_status' = ANY(changed_fields_array) 
                            THEN '"marital_status":"' || COALESCE(old_marital_status, '') || '"' END,
                        CASE WHEN 'nationality' = ANY(changed_fields_array) 
                            THEN '"nationality":"' || COALESCE(old_nationality, '') || '"' END,
                        CASE WHEN 'occupation' = ANY(changed_fields_array) 
                            THEN '"occupation":"' || COALESCE(old_occupation, '') || '"' END,
                        CASE WHEN 'birthdate' = ANY(changed_fields_array) 
                            THEN '"birthdate":"' || COALESCE(old_birthdate:: TEXT, '') || '"' END,
                        CASE WHEN 'total_asset' = ANY(changed_fields_array) 
                            THEN '"total_asset":"' || COALESCE(old_total_asset, '') || '"' END,
                        CASE WHEN 'monthly_income' = ANY(changed_fields_array) 
                            THEN '"monthly_income":"' || COALESCE(old_monthly_income, '') || '"' END
                    ], NULL),
                    ','
                ) || '}'
        END AS scalar_attribute_old_values_json,
        
        -- Build JSON object of new values (only for changed fields)
        CASE 
            WHEN ARRAY_LENGTH(changed_fields_array, 1) IS NULL THEN '{}'::TEXT
            ELSE 
                '{' || ARRAY_TO_STRING(
                    ARRAY_REMOVE(ARRAY[
                        CASE WHEN 'firstname' = ANY(changed_fields_array) 
                            THEN '"firstname":"' || COALESCE(new_firstname, '') || '"' END,
                        CASE WHEN 'lastname' = ANY(changed_fields_array) 
                            THEN '"lastname":"' || COALESCE(new_lastname, '') || '"' END,
                        CASE WHEN 'marital_status' = ANY(changed_fields_array) 
                            THEN '"marital_status":"' || COALESCE(new_marital_status, '') || '"' END,
                        CASE WHEN 'nationality' = ANY(changed_fields_array) 
                            THEN '"nationality":"' || COALESCE(new_nationality, '') || '"' END,
                        CASE WHEN 'occupation' = ANY(changed_fields_array) 
                            THEN '"occupation":"' || COALESCE(new_occupation, '') || '"' END,
                        CASE WHEN 'birthdate' = ANY(changed_fields_array) 
                            THEN '"birthdate":"' || COALESCE(new_birthdate::TEXT, '') || '"' END,
                        CASE WHEN 'total_asset' = ANY(changed_fields_array) 
                            THEN '"total_asset":"' || COALESCE(new_total_asset, '') || '"' END,
                        CASE WHEN 'monthly_income' = ANY(changed_fields_array) 
                            THEN '"monthly_income":"' || COALESCE(new_monthly_income, '') || '"' END
                    ], NULL),
                    ','
                ) || '}'
        END AS scalar_attribute_new_values_json,
        
        -- Set membership diff summary
        CASE 
            WHEN version_num_old IS NULL THEN NULL
            WHEN ARRAY_LENGTH(changed_sets_array, 1) IS NULL THEN NULL
            ELSE 
                'Changed sets: [' || ARRAY_TO_STRING(changed_sets_array, ', ') || '].  ' ||
                'See bridge tables for detailed membership changes.'
        END AS set_membership_diff_summary_text
        
    FROM with_change_detection
),

-- ====================================================================
-- Final audit records
-- ====================================================================
final AS (
    SELECT 
        -- Surrogate key (hash-based for idempotency)
        ABS(('x' || MD5(customer_id:: TEXT || effective_start_ts_new::TEXT))::BIT(63):: BIGINT) AS audit_event_id,
        
        -- Foreign keys
        customer_id,
        customer_profile_version_sk_new,
        customer_profile_version_sk_old,
        
        -- Version tracking
        version_num_new,
        version_num_old,
        
        -- Change reason
        CASE 
            WHEN version_num_old IS NULL THEN 'INITIAL_LOAD'
            ELSE 'SOURCE_UPDATE'
        END AS change_reason,
        
        -- ================================================================
        -- CHANGE METADATA (with actual values!)
        -- ================================================================
        changed_scalar_attributes_json AS changed_scalar_attributes,
        changed_set_names_json AS changed_set_names,
        scalar_attribute_old_values_json AS scalar_attribute_old_values,
        scalar_attribute_new_values_json AS scalar_attribute_new_values,
        set_membership_diff_summary_text AS set_membership_diff_summary,
        
        -- Hash tracking
        old_profile_hash,
        new_profile_hash,
        old_source_of_income_set_hash,
        new_source_of_income_set_hash,
        old_purpose_of_investment_set_hash,
        new_purpose_of_investment_set_hash,
        
        -- Data quality tracking
        old_data_quality_score,
        new_data_quality_score,
        old_data_quality_status,
        new_data_quality_status,
        
        -- Temporal tracking
        event_ts,
        effective_start_ts_new,
        effective_end_ts_old,
        CURRENT_TIMESTAMP AS load_ts,
        
        -- Lineage
        'MSSQL_CORE' AS source_system,
        NULL:: BIGINT AS etl_batch_id
        
    FROM with_json_values
)

SELECT * FROM final