{{
    config(
        materialized='incremental',
        unique_key='audit_event_id',
        schema='gold',
        tags=['gold', 'fact', 'audit']
    )
}}

-- ====================================================================
-- Gold Layer: Fact Customer Profile Audit
-- ====================================================================
-- Tracks profile change events (what changed, when, old vs new values)
-- Generated by comparing consecutive versions in dim_customer_profile
-- ====================================================================

WITH dim_all_versions AS (
    SELECT 
        customer_profile_version_sk,
        customer_id,
        version_num,
        profile_hash,
        source_of_income_set_hash,
        purpose_of_investment_set_hash,
        data_quality_score,
        data_quality_status,
        effective_start_ts,
        effective_end_ts,
        is_current
    FROM {{ ref('dim_customer_profile') }}
    
    {% if is_incremental() %}
    -- Only process new versions
    WHERE effective_start_ts > (SELECT MAX(effective_start_ts_new) FROM {{ this }})
    {% endif %}
),

-- Self-join to compare consecutive versions
version_pairs AS (
    SELECT 
        curr.customer_profile_version_sk AS customer_profile_version_sk_new,
        prev.customer_profile_version_sk AS customer_profile_version_sk_old,
        curr.customer_id,
        curr.version_num AS version_num_new,
        prev.version_num AS version_num_old,
        
        -- Hashes
        prev.profile_hash AS old_profile_hash,
        curr.profile_hash AS new_profile_hash,
        prev.source_of_income_set_hash AS old_source_of_income_set_hash,
        curr.source_of_income_set_hash AS new_source_of_income_set_hash,
        prev.purpose_of_investment_set_hash AS old_purpose_of_investment_set_hash,
        curr. purpose_of_investment_set_hash AS new_purpose_of_investment_set_hash,
        
        -- Data Quality
        prev.data_quality_score AS old_data_quality_score,
        curr.data_quality_score AS new_data_quality_score,
        prev.data_quality_status AS old_data_quality_status,
        curr.data_quality_status AS new_data_quality_status,
        
        -- Timestamps
        curr.effective_start_ts AS effective_start_ts_new,
        prev.effective_end_ts AS effective_end_ts_old,
        curr.effective_start_ts AS event_ts
        
    FROM dim_all_versions curr
    LEFT JOIN dim_all_versions prev
        ON curr.customer_id = prev.customer_id
        AND curr.version_num = prev.version_num + 1
),

final AS (
    SELECT 
        -- Surrogate key (use hash of natural key for idempotency)
        ABS(('x' || MD5(customer_id:: TEXT || effective_start_ts_new::TEXT))::BIT(63):: BIGINT) AS audit_event_id,
        
        -- Foreign keys
        customer_id,
        customer_profile_version_sk_new,
        customer_profile_version_sk_old,
        
        -- Version tracking
        version_num_new,
        version_num_old,
        
        -- Change reason
        CASE 
            WHEN version_num_old IS NULL THEN 'INITIAL_LOAD'
            ELSE 'SOURCE_UPDATE'
        END AS change_reason,
        
        -- Change metadata (simplified - full implementation would compare actual values)
        '[]'::TEXT AS changed_scalar_attributes,
        CASE 
            WHEN old_source_of_income_set_hash != new_source_of_income_set_hash 
                 OR old_purpose_of_investment_set_hash != new_purpose_of_investment_set_hash
            THEN '["source_of_income","purpose_of_investment"]'
            ELSE '[]'
        END:: TEXT AS changed_set_names,
        NULL:: TEXT AS scalar_attribute_old_values,
        '{}'::TEXT AS scalar_attribute_new_values,
        NULL::TEXT AS set_membership_diff_summary,
        
        -- Hash tracking
        old_profile_hash,
        new_profile_hash,
        old_source_of_income_set_hash,
        new_source_of_income_set_hash,
        old_purpose_of_investment_set_hash,
        new_purpose_of_investment_set_hash,
        
        -- Data quality tracking
        old_data_quality_score,
        new_data_quality_score,
        old_data_quality_status,
        new_data_quality_status,
        
        -- Temporal tracking
        event_ts,
        effective_start_ts_new,
        effective_end_ts_old,
        CURRENT_TIMESTAMP AS load_ts,
        
        -- Lineage
        'MSSQL_CORE' AS source_system,
        NULL:: BIGINT AS etl_batch_id
        
    FROM version_pairs
)

SELECT * FROM final