version: 2

models:
  - name: dim_customer_profile
    description:  "SCD Type 2 customer profile dimension with full history tracking"
    columns:
      - name: customer_profile_version_sk
        description: "Surrogate key - unique across all versions"
        tests: 
          - not_null
          - unique
      
      - name: customer_id
        description: "Natural business key - multiple versions per customer"
        tests: 
          - not_null
      
      - name: version_num
        description: "Sequential version number per customer (1, 2, 3... )"
        tests:
          - not_null
      
      - name: is_current
        description: "TRUE = latest version, FALSE = historical"
        tests:
          - not_null
      
      - name: profile_hash
        description: "SHA256 hash for change detection"
        tests:
          - not_null
      
      - name: data_quality_score
        description:  "DQ score from Silver (0-100)"
      
      - name: data_quality_status
        description: "DQ status from Silver"

  - name: bridge_customer_source_of_income
    description: "Bridge table for multi-valued source of income relationship"
    columns:
      - name: customer_profile_version_sk
        description:  "FK to dim_customer_profile"
        tests:
          - not_null
          - relationships: 
              to: ref('dim_customer_profile')
              field:  customer_profile_version_sk
      
      - name: source_of_income_code
        description: "Income source enumeration code"
        tests:
          - not_null

  - name: bridge_customer_purpose_of_investment
    description: "Bridge table for multi-valued purpose of investment relationship"
    columns:
      - name: customer_profile_version_sk
        description: "FK to dim_customer_profile"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer_profile')
              field: customer_profile_version_sk
      
      - name: purpose_of_investment_code
        description: "Investment purpose enumeration code"
        tests:
          - not_null

  - name: fact_customer_profile_audit
    description: "Audit fact tracking profile change events"
    columns:
      - name: audit_event_id
        description: "Surrogate key for audit event"
        tests:
          - not_null
          - unique
      
      - name: customer_id
        description:  "Customer affected by change"
        tests:
          - not_null
      
      - name: customer_profile_version_sk_new
        description: "FK to new version"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer_profile')
              field: customer_profile_version_sk
      
      - name: change_reason
        description: "Why version was created"
        tests:
          - not_null
          - accepted_values:
              values: ['INITIAL_LOAD', 'SOURCE_UPDATE', 'CORRECTION', 'DATA_QUALITY_FIX', 'BACKDATED_CORRECTION', 'RECOMPUTE_HASH']